import os
import shutil
from pathlib import Path
from typing import Literal

import torch
from biotite.structure.io import load_structure
from loguru import logger
from transformers import logging as hf_logging

from proteinfoundation.metrics.folding_models import run_colabfold, run_esmfold
from proteinfoundation.metrics.inverse_folding_models import run_proteinmpnn
from proteinfoundation.metrics.metric_utils import rmsd_metric
from proteinfoundation.utils.pdb_utils import extract_seq_from_pdb, load_pdb, pdb_name_from_path

hf_logging.set_verbosity_error()


# Legacy Function for Proteina
def scRMSD(
    pdb_file_path: str,
    tmp_path: str = "./tmp/metrics/",
    num_seq_per_target: int = 8,
    pmpnn_sampling_temp: float = 0.1,
    use_pdb_seq: bool = False,
    ret_min: bool = True,
    rmsd_modes: list[str] = ["ca"],
    motif_index: list[str] = None,
    motif_residue_indices: list[int] | None = None,
    folding_models: list[Literal["af2", "esmfold2", "esmfold"]] = ["esmfold"],
    cache_dir: str | None = None,
    keep_outputs: bool = False,
) -> dict[str, float | list[float]]:
    """
    Evaluates self-consistency RMSD metrics for given pdb.

    Args:
        pdb_file_path: Path to PDB file.
        tmp_path: Path to store files produced by ProteinMPNN and folding models.
        num_seq_per_target: Number of sequences generated by ProteinMPNN per structure.
        pmpnn_sampling_temp: ProteinMPNN sampling temperature.
        use_pdb_seq: Whether to use the sequence from the pdb file or call proteinMPNN to produce
            sequences.
        ret_min: Whether to return min RMSD or a list of all values.
        rmsd_modes: Which atoms to use to compute scRMSD, given as a list of strings. Valid
            modes are
            - "ca": alpha carbon
            - "bb3o": four backbone atoms [N CA C O]
            - "all_atom": uses the atom mask from the sequence from the PDB, this is only
            compatible with `use_pdb_seq=True`, since otherwise proteinMPNN will liekly
            return a different sequence and thus all atom comparisons cannot be done.
        motif_index (List[str], optional): List of positions to fix in format ["ChainID-ResidueNumber"].
            Example: ["B45", "B46", "B54"]. Defaults to None.
        motif_residue_indices (List[int], optional): List of 0-indexed residue positions to compute
            RMSD over. If provided, both normal RMSD (all residues) and motif RMSD (only these residues)
            will be computed and returned.
        folding_models: List of folding models to use for structure prediction
        cache_dir: Cache directory for model weights
        keep_outputs: Whether to keep the output files from the folding models after evaluation.
            If False (default), temporary directories containing PDB files are deleted to save space.
            If True, the folding model outputs are preserved for further analysis.

    Returns:
        A dictionary with results for each rmsd_mode and folding model (each one is a key). Values are
        either the best RMSD (scRMSD) or a list of all values for all generations,
        depending on the ret_min argument. When motif_residue_indices is provided, additional
        keys with "_motif" suffix are added containing motif-specific RMSD results.
    """
    for m in rmsd_modes:
        assert m in ["ca", "bb3o", "all_atom"], f"Invalid scRMSD mode {m}"
    if not use_pdb_seq:
        assert "all_atom" not in rmsd_modes, "`all_atom` mode not supported for scRMSD with proteinMPNN sequences"

    # Resolve and expand cache_dir (env overrides param/default; expand ~ so dirs are not created literally)
    if os.getenv("CACHE_DIR"):
        cache_dir = os.path.expanduser(os.getenv("CACHE_DIR"))
    if cache_dir:
        cache_dir = os.path.expanduser(cache_dir)
        os.environ["TORCH_HOME"] = cache_dir
        logger.info(f"Set TORCH_HOME to: {cache_dir}")

    name = pdb_name_from_path(pdb_file_path)
    os.makedirs(tmp_path, exist_ok=True)

    if not use_pdb_seq:
        logger.info("Running ProteinMPNN")
        gen_seqs = run_proteinmpnn(  # For now do not use keep ca_only=False
            pdb_file_path,
            tmp_path,
            num_seq_per_target=num_seq_per_target,
            sampling_temp=pmpnn_sampling_temp,
            fix_pos=motif_index,
        )  # List of sequences
        gen_seqs = [v["seq"] for v in gen_seqs]
        suffix = "mpnn"
    else:
        logger.info("Using sequence from pdb file")
        gen_seqs = [extract_seq_from_pdb(pdb_file_path)]  # List of sequences
        suffix = "pdb"

    results = {}
    for mode in rmsd_modes:
        results[mode] = {}
        # If motif evaluation is requested, also initialize motif results
        if motif_residue_indices is not None:
            results[f"{mode}_motif"] = {}

    # Load generated structure
    gen_prot = load_pdb(pdb_file_path)
    gen_coors = torch.tensor(gen_prot.atom_positions, dtype=torch.float32)
    gen_mask = torch.tensor(gen_prot.atom_mask, dtype=torch.bool)

    # Run each folding model
    for model in folding_models:
        logger.info(f"Running {model} for {name}")

        # Create separate directory for each folding model
        model_tmp_path = os.path.join(tmp_path, f"{model}_output")
        os.makedirs(model_tmp_path, exist_ok=True)

        # TODO: Shouldn't delete outputs inside the folding model
        if model == "esmfold":
            out_folding_paths = run_esmfold(
                gen_seqs,
                model_tmp_path,
                name,
                suffix=suffix,
                cache_dir=cache_dir,
                keep_outputs=True,  # keep_outputs
            )
        elif model == "colabfold":
            out_folding_paths = run_colabfold(
                gen_seqs,
                model_tmp_path,
                suffix=suffix,
                cache_dir=cache_dir,
                keep_outputs=keep_outputs,
            )
        # Compute RMSDs for each mode
        for mode in rmsd_modes:
            results[mode][model] = []
            # Initialize motif results if needed
            if motif_residue_indices is not None:
                results[f"{mode}_motif"][model] = []

            for out_folding in out_folding_paths:
                if out_folding is None:
                    # Handle failed predictions
                    results[mode][model].append(float("inf"))
                    if motif_residue_indices is not None:
                        results[f"{mode}_motif"][model].append(float("inf"))
                    continue

                rec_prot_folding = load_pdb(out_folding)
                rec_coors = torch.tensor(rec_prot_folding.atom_positions, dtype=torch.float32)
                rec_mask = torch.tensor(rec_prot_folding.atom_mask, dtype=torch.bool)
                mask = gen_mask * rec_mask

                # Compute normal RMSD (all residues)
                normal_rmsd = rmsd_metric(
                    coors_1_atom37=gen_coors,
                    coors_2_atom37=rec_coors,
                    mask_atom_37=mask,
                    mode=mode,
                    residue_indices=None,  # All residues
                )
                results[mode][model].append(normal_rmsd)

                # Compute motif RMSD if requested
                if motif_residue_indices is not None:
                    motif_rmsd = rmsd_metric(
                        coors_1_atom37=gen_coors,
                        coors_2_atom37=rec_coors,
                        mask_atom_37=mask,
                        mode=mode,
                        residue_indices=motif_residue_indices,  # Only motif residues
                    )
                    results[f"{mode}_motif"][model].append(motif_rmsd)

        # Clean up model-specific directory to save space
        try:
            if keep_outputs:
                logger.info(f"Keeping {model} output directory: {model_tmp_path}")
            else:
                shutil.rmtree(model_tmp_path)
                logger.info(f"Cleaned up {model} output directory: {model_tmp_path}")
        except Exception as cleanup_error:
            logger.warning(f"Could not clean up {model} directory {model_tmp_path}: {cleanup_error}")

    if ret_min:
        return {m: {model: min(results[m][model]) for model in folding_models} for m in results}
    return results


def run_multimer_eval(
    pdb_file_path: str | Path,
    tmp_path: str | Path = "./tmp/metrics/",
    folding_method: str = "esmfold",
) -> tuple[list[str], list[dict[str, dict]], list[dict[str, float | str]]]:
    """Evaluates protein multimer designs using structure prediction models.

    This function takes a PDB file containing a protein multimer design and evaluates it using
    ESMFold. The function first extracts sequences from ProteinMPNN output,
    then predicts structures for these sequences using the specified folding method.

    Args:
        pdb_file_path: Path to the input PDB file containing the multimer design.
        tmp_path: Directory to store temporary files and results.
            Defaults to "./tmp/metrics/".
        folding_method: Structure prediction method to use. Must be either "esmfold"
            or "alphafold2". Defaults to "esmfold".

    Returns:
        A tuple containing:
            - List of paths to the generated PDB files containing predicted structures
            - List of dictionaries with folding statistics for each sequence
            - List of dictionaries with RMSD results for each sequence

    Raises:
        ValueError: If folding_method is not "esmfold" or "alphafold2".

    Note:
        The function expects ProteinMPNN output files to be present in the tmp_path directory
        under the "seqs" subdirectory with the same base name as the input PDB file.
    """

    name = pdb_name_from_path(pdb_file_path)
    logger.info("Running ProteinMPNN")

    mpnn_sequences = run_proteinmpnn(  # For now do not use keep ca_only=False
        pdb_file_path,
        tmp_path,
        all_chains=None,
        pdb_path_chains=[],
        fix_pos=None,
        num_seq_per_target=20,
        omit_AAs="C",
        sampling_temp=0.1,
        verbose=False,
    )  # list with dictionaries containing sequences, scores etc

    logger.info("ProteinMPNN finished")
    logger.info(f"Running {folding_method} for {name}")

    if folding_method == "esmfold":
        sequences = [seq["seq"].replace("/", ":") for seq in mpnn_sequences]
        pdb_paths, stats = run_esmfold_multimer(sequences, os.path.join(tmp_path, "esmfold"))
    else:
        raise ValueError(f"Unsupported folding method: {folding_method}")

    rmsd_results = []
    for seq_num, pdb_path in enumerate(pdb_paths):
        gen_prot = load_pdb(pdb_file_path)
        gen_coors = torch.tensor(gen_prot.atom_positions, dtype=torch.float32)
        fold_prot = load_pdb(pdb_path)
        fold_coors = torch.tensor(fold_prot.atom_positions, dtype=torch.float32)
        try:
            rmsd_result = rmsd_metric(gen_coors, fold_coors)
        except:
            logger.error(f"Error in {pdb_path}")
            rmsd_result = float("inf")
        rmsd_results.append({f"seq_{seq_num + 1}": rmsd_result})

    return pdb_paths, stats, rmsd_results


def run_esmfold_multimer(
    seqs: list[str],
    path_to_esmfold_out: str,
) -> tuple[list[str], list[dict[str, dict[str, float]]]]:
    """Runs ESMFold structure prediction on multiple sequences.

    This function takes a list of protein sequences and predicts their structures
    using ESMFold. It handles multimer sequences (separated by ':') and computes
    confidence metrics for each prediction.

    Args:
        seqs: List of protein sequences. For multimers, chains should be separated by ':'.
        path_to_esmfold_out: Output directory where PDB files will be saved.

    Returns:
        A tuple containing:
            - List of paths to the generated PDB files
            - List of dictionaries with statistics for each prediction,
              containing pLDDT scores

    Note:
        The function loads the ESMFold model onto GPU and processes sequences
        sequentially. Existing files are skipped to avoid recomputation.
    """
    import esm

    stats = []
    os.makedirs(path_to_esmfold_out, exist_ok=True)
    esm_model = esm.pretrained.esmfold_v1()
    esm_model = esm_model.eval().cuda()
    out_esm_paths = []
    for seq_num, seq in enumerate(seqs):
        fname = f"esm_{seq_num + 1}.pdb"
        fdir = os.path.join(path_to_esmfold_out, fname)
        if os.path.exists(fdir):
            logger.info(f"Skipping {fname} because it already exists")
        else:
            with torch.no_grad():
                output = esm_model.infer_pdb(seq)
            with open(fdir, "w") as f:
                f.write(output)
        out_esm_paths.append(fdir)

        struct = load_structure(fdir, extra_fields=["b_factor"])
        pLDDT = struct.b_factor.mean()
        stat = {
            "pLDDT": round(pLDDT, 2),
        }
        stats.append({f"seq_{seq_num + 1}": stat})

    return out_esm_paths, stats
